### PR TITLE
Remove closet sexism

### PR DESCRIPTION
**Pull request by seutje**
Same joke, less sexist.

### CODE REVIEW

**Comment by minecrawler** [comment]
I think, that term was part of the joke. It's an established phrase. I do not think of it as being sexist.
It's a shame all this gender rage lately tries to neutralize everything to one big pile of grey sameness.

Really now, it's just a joke!

**Comment by LinAGKar** [comment]
Real programmers is also an established phrase https://xkcd.com/378/. Honestly, while I don't care much for the PC culture, I think this fits better. Not all real men are real programmers.

**Comment by polendri** [comment]
@minecrawler: "_Real_ _Xs_ never _Y_" is a saying of its own; it doesn't need to be "men" in order to make sense. There's also nothing in the joke that plays on male bravado, so it arguably makes more sense as "programmers". It seems a little insensitive honestly to be complaining about political correctness gone too far over someone wanting to eliminate a clear "programmers = men" implication by changing a single word. It's bikeshedding even having a conversation about it IMO.

**Comment by binary132** [comment]
Real men never merge these kinds of pull requests.

**Comment by brycedrennan** [comment]
This whole piece is a satire. If there is sexism in it, then I'd read that as part of the satire. 

I read this little bit of "sexism" as making fun of the male bravado stereotype.

**Comment by Alir3z4** [comment]
I don't think any pull request that tries to change sentences or any such should be accepted.
If there's a typo or Markdown syntax then yeah.

Real men never merge these kinds of pull requests.

**Comment by Nakilon** [comment]
This pull request is a sexism.

**Comment by caseyfw** [comment]
I agree that this should be merged - 'real programmers' makes far more sense in this context than 'real men', despite the fact that the latter is indeed an existing, albeit unnecessarily gender-charged expression.

**Comment by cajhne** [comment]
Real programmers ftw. Some of the comments here need pull requests of their own. Real men often aren't.

**Comment by Droogans** [comment]
Thanks for your suggestion, @seutje. Although many commenters here have made good points about this suggested update, it does not fit the intention of this project.

See https://github.com/Droogans/unmaintainable-code/issues/19 for details. Please limit all contributions to grammar fixes, punctuation errors, typos, and other non-semantic changes to the style or writing in any way.

**Comment by shnbwmn** [comment]
Thank you for not merging this ridiculous pull request.

**Pull request closed without merging**
